### ISSUE TITLE
[BUG] LastSubmenu.func is not a function

### ISSUE THREAD

**Issue by stevenqu248** [AlderArts/foe#367] opened 2015-09-25 03:44 UTC
Edit: This error occurs on both the offline and online version of the game. Also, sorry for the bad title. I'm really bad at naming things.

1. If I move around in the menus in a certain way, I get an error saying that the java script is calling a bad function.
2. Starting from a new game. create a character and get to the point where you have just grabbed the gem and are in the barrens before you have chosen a name (I was able to recreate the bug after naming myself). Click on your portrait, then click on the data tab directly above the portrait. After having done that, click on the back button. The error message will occur then. If you don't click on your portrait first and only click on the data tab and select back, no issues will occur. If you select your portrait and then select back, no issues will occur. It is only this selection: Character Page->Data->Back.
3. There's no game text that appears. This is the error message, though: 
LastSubmenu.func is not a function.........PrintDefaultOptions@http://www.fenoxo.com/play/FoE/foe.js:306:764
Button.prototype.HandleClick@http://www.fenoxo.com/play/FoE/foe.js:46:2234
Button/<@http://www.fenoxo.com/play/FoE/foe.js:46:1935
Bd</e@http://www.fenoxo.com/play/FoE/foe.js:32:2696
4. I have not been able to get to a point in the game where the save function has been able to be used.

**Comment by aldergames** [comment] 2015-09-25 06:01
Hrm, I'm unable to reproduce this bug, neither in the current github version nor in the version currently online on fenoxo.com. I've tested both FF and Chrome, following the steps you suggested.

**Comment by stevenqu248** [comment] 2015-09-26 00:45
Hmm, then I don't know. I am using Firefox. I have no idea what is going on then. I'll try again. It could be just some weird thing with my version of Windows. I am using Windows 8.1. I don't think that could be the problem. It could just be my machine, in which case I wouldn't want you to keep this issue open, just because of me. It didn't seem to remove anything from the game. I'll just have to remember not to navigate through the menus in that fashion. Thanks anyway.

**Comment by aldergames** [comment] 2015-09-26 13:38
OS should not make any difference.

Does the bug still appear in 0.4L?

**Comment by aldergames** [comment] 2015-10-10 15:16
Closing this due to not being able to reproduce bug.

**Closed by aldergames** 2015-10-10 15:16 UTC
Labels: bug
